name: Gen Debug Keystore
on: workflow_dispatch

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate
        run: |
          keytool -genkey -v -keystore debug.keystore \
            -storepass android -keypass android \
            -alias androiddebugkey -keyalg RSA -keysize 2048 \
            -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          echo "-----BEGIN KEYSTORE-----"
          base64 -w 0 debug.keystore
          echo "-----END KEYSTORE-----"
